server:
  port: 8081

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pulsewatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:pulsewatch-super-secret-jwt-key-2024}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

logging:
  level:
    com.pulsewatch.usermanagement: DEBUG
    org.springframework.security: DEBUG 