server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pulsewatch
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 