server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Service, user-service
        
        - id: monitoring-service
          uri: http://localhost:8082
          predicates:
            - Path=/metrics/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Service, monitoring-service

        - id: uptime-service
          uri: http://localhost:8083
          predicates:
            - Path=/uptime/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Service, uptime-service

        - id: alerting-service
          uri: http://localhost:8084
          predicates:
            - Path=/alerts/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Gateway-Service, alerting-service

      default-filters:
        - AddRequestHeader=X-Gateway-Timestamp, "#{T(java.time.Instant).now()}"
        - AddRequestHeader=X-Gateway-ID, "#{T(java.util.UUID).randomUUID()}"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.pulsewatch.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 